name: Test Tier 2

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to use'
        required: true
        type: string

jobs:
  message:
    name: ${{ inputs.environment }} - Tier 2 Message
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "::notice::${{ vars.env_message }}"
